app/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin

from app.views import root
from product import urls as product_urls

urlpatterns = [
    url(r'^$', root, name='root'),
    url(r'^products/', include(product_urls, namespace='products')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

product/urls.py
from django.conf.urls import url

from product.views import products, products_alternate

urlpatterns = [
    url(r'^$', products, name='list'),
    url(r'^alt/$', products_alternate, name='list_alt'),
]

product/models.py
# coding: utf-8
from __future__ import unicode_literals

from datetime import datetime

from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation


class Discount(models.Model):
    limit = models.Q(app_label='product', model='product') \
            | models.Q(app_label='product', model='category') \
            | models.Q(app_label='product', model='brand')
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE,
                                     limit_choices_to=limit)
    object_id = models.PositiveIntegerField()
    item = GenericForeignKey('content_type', 'object_id')

    in_percents = models.PositiveSmallIntegerField('размер скидки, %', default=0)
    begin = models.DateTimeField('действует с', default=datetime.now, blank=True)
    end = models.DateTimeField('действует по', default=datetime.now, blank=True)

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):

        if not isinstance(self.item, (Product, Category, Brand, )):
            raise Exception('You can add discount only for product, category or brand.')

        super(Discount, self).save(force_insert, force_update, using, update_fields)


class Category(models.Model):
    name = models.CharField('группа товаров', max_length=64)
    discount = GenericRelation(Discount, related_query_name='category')


class Brand(models.Model):
    name = models.CharField('бренд', max_length=64)
    discount = GenericRelation(Discount, related_query_name='brand')


class CatalogManager(models.Manager):

    def catalog(self):
        from django.db.models import Case, When, F, Q, Value, IntegerField, DecimalField
        from django.db.models.functions import Greatest, Now, Cast

        p_date_filter = Q(discount__end__gte=Now()) & Q(discount__begin__lte=Now())
        c_date_filter = Q(category__discount__end__gte=Now()) & Q(category__discount__begin__lte=Now())
        b_date_filter = Q(brand__discount__end__gte=Now()) & Q(brand__discount__begin__lte=Now())

        return self.get_queryset().filter(
            price__gte=1000,
            price__lte=10000
        ).annotate(
            product_discount=Case(
                When(p_date_filter, then=F('discount__in_percents')), default=Value(0), output_field=IntegerField(),
            )
        ).annotate(
            category_discount=Case(
                When(c_date_filter, then=F('category__discount__in_percents')), default=Value(0),
                output_field=IntegerField(),
            )
        ).annotate(
            brand_discount=Case(
                When(b_date_filter, then=F('brand__discount__in_percents')), default=Value(0),
                output_field=IntegerField(),
            )
        ).annotate(
            total_cost=Cast(
                F('price') * (1 - Greatest('product_discount', 'category_discount', 'brand_discount') / 100.0),
                DecimalField(max_digits=10, decimal_places=2)
            )
        ).values('id', 'name', 'product_discount', 'category_discount',
                 'brand_discount', 'total_cost', 'price')


class Product(models.Model):
    category = models.ForeignKey(Category, verbose_name='группа товара', null=True,
                                 blank=True, on_delete=models.SET_NULL)
    brand = models.ForeignKey(Brand, verbose_name='группа', null=True,
                              blank=True, on_delete=models.SET_NULL)
    name = models.CharField('название товара', max_length=128)
    price = models.DecimalField('стоимость единицы, руб.', max_digits=10, decimal_places=2, default=0)
    discount = GenericRelation(Discount, related_query_name='product')

    objects = CatalogManager()


class TotalDiscount(models.Model):
    """ Модель представлена как одно из возможных решений. Решение заключается в добавлении представления(вьюхи) в бд и
    написание необслуживаемой модели(TotalDiscount) для получения данных из вьюхи средствами ORM. Если сделать Explain
    для запроса на создание вьюхи и получения данных из нее, то Postgres утверждает, что вьюха будет работать до 2х раз
    быстрее, чем решение на чистом ORM (без добавления вьюхи и необслуживаемой модели). НО! запрос через ORM выполняются
    быстрее(процентов на 15-20), чем с использованием данной модели(Explain врет?). Еще, данное решение будет труднее
    сопровождать - менять миграции в случае изменения структуры или типа БД, потому данный способ получения
    каталога стоит рассматривать как альтернативный.(возможно, он имеет право на жизнь при более сложных условиях
    группировок и фильтраций)"""

    id = models.BigIntegerField(primary_key=True)
    product = models.ForeignKey(Product, on_delete=models.DO_NOTHING)
    name = models.CharField('название товара', max_length=128)
    category = models.ForeignKey(Category, on_delete=models.DO_NOTHING)
    brand = models.ForeignKey(Brand, on_delete=models.DO_NOTHING)
    price = models.DecimalField('стоимость единицы, руб.', max_digits=10, decimal_places=2)
    product_discount = models.PositiveSmallIntegerField('скидка на товар, %')
    category_discount = models.PositiveSmallIntegerField('скидка на группу товаров, %')
    brand_discount = models.PositiveSmallIntegerField('скидка на брэнд, %')
    total_cost = models.DecimalField('стоимость с учетом максимальной скидки, руб.', max_digits=10, decimal_places=2)

    class Meta:
        managed = False
        db_table = 'total_discounts'

app/views.py
from django.shortcuts import render, redirect
from django.urls import reverse


def root(request):

    return redirect(reverse('products:list'))

product/views.py
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import JsonResponse
from django.shortcuts import render

from product.models import TotalDiscount, Product


def products(request):

    result = TotalDiscount.objects.filter(
        price__gte=1000,
        price__lte=10000
    ).values('product_id', 'name', 'product_discount', 'category_discount',
             'brand_discount', 'total_cost', 'price')

    if request.GET.get('sort') == 'desc':
        result = result.order_by('-total_cost')
    else:
        result = result.order_by('total_cost')

    paginator = Paginator(result, 25)

    page = request.GET.get('page')
    try:
        result = paginator.page(page)
    except PageNotAnInteger:
        result = paginator.page(1)
    except EmptyPage:
        result = paginator.page(paginator.num_pages)

    if request.GET.get('format') == 'json':
        return JsonResponse({'result': list(result)})

    return render(request, 'catalog.html', {'result': list(result), 'num_pages': result.paginator.num_pages})


def products_alternate(request):

    result = Product.objects.catalog()

    if request.GET.get('sort') == 'desc':
        result = result.order_by('-total_cost')
    else:
        result = result.order_by('total_cost')

    paginator = Paginator(result, 25)

    page = request.GET.get('page')
    try:
        result = paginator.page(page)
    except PageNotAnInteger:
        result = paginator.page(1)
    except EmptyPage:
        result = paginator.page(paginator.num_pages)

    if request.GET.get('format') == 'json':
        return JsonResponse({'result': list(result)})

    return render(request, 'catalog.html', {'result': list(result), 'num_pages': result.paginator.num_pages})

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="content-type" content="text/html; charset=utf-8">
	<title>debug</title>

{#    <link rel="stylesheet" href="{% static ".css" %}">#}
    <style>
        a.button {
            -webkit-appearance: button;
            -moz-appearance: button;
            appearance: button;

            text-decoration: none;
            color: initial;

            padding: 5px;
            margin-right: 20px;
        }
    </style>

</head>
<body>
    <div style="margin-bottom: 30px;">
        <a id="notmanaged" href="{% url 'products:list' %}" class="button">получение каталога через вьюху(бд)</a>
        <a id="orm" href="{% url 'products:list_alt' %}" class="button">получение каталога через orm</a>
        <span>страница </span>
        <input type="number" value="" placeholder="номер">
        <span>из {{ num_pages }}</span>
    </div>
	{% block content %}{% endblock %}
    <script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
    <script>
        var getParam = function getUrlParameter(sParam) {
            var sPageURL = decodeURIComponent(window.location.search.substring(1)),
                sURLVariables = sPageURL.split('&'),
                sParameterName,
                i;

            for (i = 0; i < sURLVariables.length; i++) {
                sParameterName = sURLVariables[i].split('=');

                if (sParameterName[0] === sParam) {
                    return sParameterName[1] === undefined ? true : sParameterName[1];
                }
            }
        };
        $(window).ready(function () {
            var curPage = getParam('page');
            var $input = $('input').val(curPage);
        });
        $('a').click(function(e) {
            e.preventDefault();
            var $input = $(this).parent().find('input');
            var actualValue = $input.val();
            if (!actualValue) {
                actualValue = '1';
            }
            location.href = this.href + '?page=' + actualValue
        })
    </script>
</body>


</html>

templates/catalog.html
{% extends 'base.html' %}

{% block content %}
    <table cellspacing="2" border="1" cellpadding="5" width="900">
        <thead>
            <tr>
                <th>название</th>
                <th>обычная цена</th>
                <th>скидка на товар</th>
                <th>скидка на категорию</th>
                <th>скидка на брэнд</th>
                <th>итоговая цена</th>
            </tr>
        </thead>
        <tbody>
            {% for item in result %}
                <tr>
                    <td>{{ item.name }}</td>
                    <td>{{ item.price }}</td>
                    <td>{{ item.product_discount }}</td>
                    <td>{{ item.category_discount }}</td>
                    <td>{{ item.brand_discount }}</td>
                    <td>{{ item.total_cost }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/index.html
{% load cache %}
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <title>Index of Tests</title>
</head>
<body>
    <h1>Index of Tests</h1>
    {% cache 10 index_cache %}
    <ul>
        <li><a href="/jquery/">jQuery 2.0.3</a></li>
        <li><a href="/mootools/">MooTools 1.4.5</a></li>
        <li><a href="/prototype/">Prototype 1.7.1.0</a></li>
    </ul>
    <p><a href="/admin/">Django Admin</a></p>
    {% endcache %}
</body>
</html>